---
name: Xray
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["ui-test (manual)"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    # if: github.ref == 'feature/test.7.0'
    steps:
      - name: Start Xray
        run: echo "Hello Xray"